### ISSUE TITLE
Peticiones http

### ISSUE THREAD

**Issue by Patriigb** [UNIZAR-30226-2023-07/Backend#9]

**Comment by 815177** [comment]
26/03/2023 Añadidas peticiones de lista de amigos, eliminar amistad y modificar información del jugador.
Faltan pruebas, aunque se han añadido datos aleatorios de prueba.

**Comment by 815177** [comment]
28/03/23 Añadidas peticiones de Chat.

**Comment by 815177** [comment]
20/04/23 Añadidas peticiones de unirse, crear e iniciar una partida
